receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  resource:
    attributes:
      - key: appdynamics.controller.account
        action: upsert
        value: "my-appd-account"
      - key: appdynamics.controller.host
        action: upsert
        value: "my-controller-host"
      - key: appdynamics.controller.port
        action: upsert
        value: 443
  batch:

exporters:
  #prometheus:
    #endpoint: "0.0.0.0:8889"
    #namespace: promexample
    #const_labels:
      #label1: value1

  #zipkin:
    #endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    #format: proto

  logging:
    loglevel: debug

  jaeger:
    endpoint: host.docker.internal:14250
    insecure: true

  otlphttp:
    endpoint: https://my-appd-endpoint.com
    headers: {"x-api-key": "${X_API_KEY}"}

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      #exporters: [logging, zipkin, jaeger]
      exporters: [logging, jaeger, otlphttp]
    #metrics:
      #receivers: [otlp]
      #processors: [batch]
      #exporters: [logging, prometheus]
